compile :
	gcc t09_01.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t09_01 -Wall
	gcc t09_02.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t09_02 -Wall
	gcc t09_03.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t09_03 -Wall

test_01 :
	./t09_01

test_02 :
	./t09_02

test_03 :
	./t09_03
