compile :
	gcc t08_01.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t08_01 -Wall
	gcc t08_02.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t08_02 -Wall

test_01 :
	./t08_01

test_02 :
	./t08_02
