compile :
	gcc t07_01.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t07_01 -Wall
	gcc t07_02.c ./libs/gender.c ./libs/dorm.c ./libs/student.c -o t07_02 -Wall

test_01 :
	./t07_01

test_02 :
	./t07_02
