compile :
	gcc t06_01.c StudentDormitory.c -o t06_01
	gcc t06_02.c StudentDormitory.c -o t06_02
	gcc t06_03.c StudentDormitory.c -o t06_03

test_01 :
	./t06_01

test_02 :
	./t06_02

test_03 :
	./t06_03
