compile :
	gcc t10_01.c ./libs/gender.c ./libs/dorm.c ./libs/student.c ./libs/repository.c -o t10_01 -Wall
	gcc t10_02.c ./libs/gender.c ./libs/dorm.c ./libs/student.c ./libs/repository.c -o t10_02 -Wall

test_01 :
	./t10_01

test_02 :
	./t10_02
